/**
 * Same-origin stylesheet for the web fonts a generated site uses.
 *
 * This used to hot-link Google Fonts (self-hosting was deferred to "Phase 4").
 * The fonts are now self-hosted under apps/sites/public/fonts (generated by
 * scripts/fetch-fonts.ts), so live customer sites make no third-party font
 * request — a UK-GDPR / third-party-request / performance win.
 *
 * One stylesheet covers every FONT_PAIRS family; the @font-face set is small,
 * so a single same-origin link is simpler than per-pair stylesheets.
 */
export function selfHostedFontsHref(): string {
  return '/fonts/fonts.css'
}
